### ISSUE TITLE
Naming (PersistentMap vs PMap …)

### ISSUE THREAD

**Issue by tosh** [vacuumlabs/persistent#63]
Is there a reason for the name change?
I fear we unnecessarily lost some clarity and familiarity here?

https://www.dartlang.org/articles/api-naming-guide/#avoid-abbreviations

Clojure also seems to use `PersistentMap` etc:
http://clojure.org/data_structures

**Comment by tomaskulich** [comment]
Well, sure, there is some trade-off between brevity and clarity here.

For me, the important moment was, when we used persistents in the real project. Cluttering your code with long names was unpleasant; people started to type their code less (they used var instead of proper type).

In Clojure, the situation is quite different: almost never you type 'PersistentMap' into your project (well, unless you develop the persistent structures themselves).

Originally, I also preferred clarity to brevity; however, even on project of a TodoList size, this was more painful than I'd like.

**Comment by tosh** [comment]
Thanks for the explanation.
